[package]
name = "ndi-sdk-sys"
version = "0.1.0"
edition = "2024"

[features]
strict_assertions = []

[build-dependencies]
bindgen = "0.71"

[dependencies]
num = "0.4.3"
num_enum = "0.7.3"
static_assertions = "1.1.0"

[dev-dependencies]
strum = { version = "0.27.1", features = ["derive"] }
